import React, { createContext, useContext, useEffect, useState } from "react";

export type Language = "en" | "es";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionary
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    "nav.benefits": "Benefits",
    "nav.courses": "Courses",
    "nav.howItWorks": "How It Works",
    "nav.faq": "FAQ",
    "nav.getCard": "GET YOUR MEMBERSHIP",
    "nav.login": "Login",
    "nav.dashboard": "Dashboard",

    // Sticky mobile CTA (home)
    "sticky.subline": "per year · {{count}} courses",

    // Hero
    "hero.location": "EXCLUSIVE FOR PUERTO RICO RESIDENTS",
    "hero.playMore": "Play More.",
    "hero.payLess": "Pay Less.",
    "hero.description": "One membership unlocks up to 25% off green fees at Puerto Rico's finest courses — from TPC Dorado Beach to Royal Isabela.",
    "hero.stats.courses": "PARTNER COURSES",
    "hero.stats.savings": "MAX SAVINGS",
    "hero.stats.price": "PER YEAR",
    "hero.cta": "GET YOUR MEMBERSHIP — $199/YR",
    "hero.viewCourses": "VIEW ALL COURSES",

    // Benefits
    "benefits.label": "WHY JOIN",
    "benefits.heading": "Why Join Links Golf?",
    "benefits.description": "Everything you need to play more and pay less at Puerto Rico's finest courses.",
    "benefits.cta": "BECOME A MEMBER",
    "benefits.savings.highlight": "UNBEATABLE SAVINGS",
    "benefits.savings.title": "Save Big on Every Round",
    "benefits.savings.body": "Save up to $200 per year with 25% discounts on green fees.",
    "benefits.card.highlight": "DIGITAL PASS",
    "benefits.card.title": "Your Pass, Your Wallet",
    "benefits.card.body": "Photo-verified, non-transferable ID. No physical card needed.",
    "benefits.identity.highlight": "INSTANT ACCESS",
    "benefits.identity.title": "Play Immediately",
    "benefits.identity.body": "Play immediately at all 15 partner courses with your digital pass.",
    "benefits.price.highlight": "NO BLACKOUT DATES",
    "benefits.price.title": "Play When You Want",
    "benefits.price.body": "Play whenever you want—weekdays, weekends, holidays.",
    "benefits.stats.partnerCoursesLabel": "Partner courses",
    "benefits.stats.maxDiscountLabel": "Max discount",
    "benefits.stats.breakEvenLabel": "Rounds to break even",
    "benefits.stats.breakEvenRange": "3–4",

    // Courses
    "courses.label": "OUR NETWORK",
    "courses.heading": "15 Partner Courses",
    "courses.description": "Play at Puerto Rico's finest courses with your membership.",
    "courses.bottomText": "Explore all 15 courses in our network.",
    "courses.viewAll": "View full course directory",
    "courses.filter.all": "ALL",
    "courses.filter.resort": "RESORT",
    "courses.filter.club": "CLUB",
    "courses.filterLabel": "Filter by course type",
    "courses.discountOff": "OFF",
    "courses.discount": "discount",
    "courses.mapInfo": "{{count}} courses shown",
    "courses.mapCloseDetail": "Close course details",
    "courses.viewList": "List",
    "courses.viewMap": "Map",
    "courses.viewModeGroup": "List or map view",
    "courses.homeFilter.all": "All",
    "courses.homeFilter.resort": "Resort",
    "courses.homeFilter.semiPrivate": "Semi-Private",
    "courses.homeFilter.public": "Public",
    "courses.homeFilter.countryClub": "Country Club",

    // How It Works
    "howItWorks.title": "From sign-up to first tee in minutes.",
    "howItWorks.step1": "Sign Up",
    "howItWorks.step1Desc": "Provide your details and upload a selfie.",
    "howItWorks.step2": "Get Your Card",
    "howItWorks.step2Desc": "Digital pass appears instantly in your wallet.",
    "howItWorks.step3": "Play",
    "howItWorks.step3Desc": "Show your pass at any partner course and enjoy your discount.",

    // Pricing
    "pricing.title": "Start playing more today.",
    "pricing.subtitle": "Unlock every major course in Puerto Rico. Pays for itself in as few as 3–4 rounds.",
    "pricing.price": "$199",
    "pricing.period": "/year",
    "pricing.residentOnly": "PUERTO RICO RESIDENTS ONLY",
    "pricing.details": "DETAILS",
    "pricing.payment": "PAYMENT",
    "pricing.digitalId": "DIGITAL ID",
    "pricing.annualMembership": "Annual Membership",
    "pricing.paymentMethodDesc": "Select your payment method",
    "pricing.subscribeNow": "Subscribe Now",
    "pricing.buyOnceNow": "Buy Once Now",
    "pricing.securedByStripe": "Secured by Stripe",
    "pricing.playerDetails": "Player Details",
    "pricing.firstName": "First Name",
    "pricing.lastName": "Last Name",
    "pricing.phone": "Phone",
    "pricing.email": "Email Address",
    "pricing.address": "Address",
    "pricing.verificationPhoto": "Verification Photo",
    "pricing.photoRequired": "Required: Front-facing. Used for Digital ID only.",
    "pricing.takeUploadPhoto": "Take or Upload Photo",
    "pricing.continuePayment": "CONTINUE TO PAYMENT",
    "pricing.savingForm": "Saving…",
    "pricing.savePhoto": "Save photo",
    "pricing.choosePhoto": "Please choose a photo.",
    "pricing.savePhotoError": "Failed to save your photo. Please try again.",
    "pricing.memberNoLabel": "Member No.",
    "pricing.validUntilLabel": "Valid until",
    "pricing.seasonLabel": "Season",
    "pricing.payNow": "PAY $199 & GET YOUR MEMBERSHIP",
    "pricing.cardNumber": "Card Number",
    "pricing.expiry": "EXPIRY",
    "pricing.cvv": "CVV",
    "pricing.nameOnCard": "Name on Card",
    "pricing.terms": "Terms of Service",
    "pricing.privacy": "Privacy Policy",
    "pricing.agree": "By continuing, you agree to our",
    "pricing.success": "You're in.",
    "pricing.successDesc":
      "Membership active. A confirmation has been sent to your email.",
    "pricing.postPhotoHeading": "One last step — add your photo.",
    "pricing.postPhotoBody":
      "Your wallet pass is photo-bound, so we can't issue it without a verified photo. It only appears on your Digital ID and is never shared.",
    "pricing.postPhotoFooter": "Required · Front-facing · Used for your Digital ID only.",
    "pricing.savingPhoto": "Saving…",
    "pricing.walletDisabledHint":
      "Add your photo above to enable Apple Wallet and Google Wallet.",
    "pricing.addAppleWallet": "Add to Apple Wallet",
    "pricing.addGoogleWallet": "Add to Google Wallet",
    "pricing.goToDashboard": "GO TO MY DASHBOARD",
    "pricing.checkEmail": "Check your email for membership details and course information.",
    "pricing.features.courses": "Access to 15 partner courses",
    "pricing.features.savings": "Up to 25% off green fees",
    "pricing.features.wallet": "Digital pass in your wallet",
    "pricing.features.verified": "Photo-verified ID",
    "pricing.features.reissue": "Free reissue if lost",
    "pricing.features.noBlackout": "No blackout dates",

    "pricing.residencyGateTitle": "Confirm eligibility",
    "pricing.residencyCheckbox": "I confirm I am a bona fide Puerto Rico resident.",
    "pricing.agreeTermsLead": "I have read and agree to the",
    "pricing.agreePrivacyLead": "I have read and agree to the",
    "pricing.agreeRefundLead": "I have read the",
    "pricing.mustAcceptLegal": "Please confirm eligibility and accept all policies above to continue.",
    "pricing.checkoutHelpLead": "Questions before checkout? Email ",
    "pricing.paymentRefundReminder": "You are about to pay the annual fee. Review",

    "memberCard.wordmark": "Links Golf Membership",

    "trustStrip.headline": "Built for year-round play in Puerto Rico",
    "trustStrip.col1Value": "{{count}}",
    "trustStrip.col1Label": "Partner courses",
    "trustStrip.col2Value": "25%",
    "trustStrip.col2Label": "Max green fee savings",
    "trustStrip.col3Value": "365",
    "trustStrip.col3Label": "Days to play every year",

    // FAQ
    "faq.label": "FAQ",
    "faq.heading": "Common questions.",
    "faq.title": "Common questions.",
    "faq.q1": "What is Links Golf Membership?",
    "faq.a1": "Your all-in-one membership to premium golf across Puerto Rico. Instant access to exclusive discounts of every partner course, a digital wallet pass, and a verified photo ID — no physical card needed.",
    "faq.q2": "Who can join?",
    "faq.a2": "Puerto Rico residents only. When you join you confirm that you meet our eligibility rules. Partner courses verify identity when you check in to play (including government-issued photo ID when they require it), which is standard in Puerto Rico. Your member discount applies only when the course confirms you qualify under its policies. We may also ask for residency or ID in the membership experience if needed for fraud prevention or account support. Providing false information may void your membership.",
    "faq.q3": "Do I need to download an app?",
    "faq.a3": "No. Your membership lives in your phone's native wallet (Apple Wallet or Google Pay). Just show your pass at the course.",
    "faq.q4": "How do I use it at the course?",
    "faq.a4": "Open your wallet, show your Links Golf pass to the pro shop, and enjoy your discount. It's that simple.",
    "faq.q5": "What if I lose my phone?",
    "faq.a5": "Your pass is tied to your account. Log in from any device and re-add it to your wallet.",
    "faq.q6": "Is the membership transferable?",
    "faq.a6": "No. Your photo-verified pass is non-transferable and tied to your identity.",
    "faq.q7": "When does my membership renew?",
    "faq.a7": "Your membership renews annually on the anniversary of your sign-up date. You'll receive a renewal reminder 30 days before expiration.",
    "faq.q8": "How do refunds and cancellations work?",
    "faq.a8Lead": "Read the full policy here:",
    "faq.refundsPageLink": "Refunds & cancellations",
    "faq.a8Trail": "It explains cooling-off timing, when fees become non-refundable, and how to reach us about billing.",
    "faq.stillHaveQuestions": "Still have questions?",
    "faq.contactUs": "Contact us at",

    // Footer
    "footer.tagline": "Unlock Puerto Rico's finest courses with one membership.",
    "footer.membership": "MEMBERSHIP",
    "footer.legal": "LEGAL",
    "footer.benefits": "Benefits",
    "footer.ourNetwork": "Our Network",
    "footer.howItWorks": "How It Works",
    "footer.getYourCard": "Get Your Card",
    "footer.faq": "FAQ",
    "footer.contactUs": "Contact Us",
    "footer.email": "info@linksgolfpr.com",
    "footer.copyright": "© 2026 Links Golf. All rights reserved.",
    "footer.supportTitle": "Support",
    "footer.terms": "Terms of Service",
    "footer.privacy": "Privacy Policy",
    "footer.bottom.residency": "© 2026 Links Golf Membership. Puerto Rico residents only.",
    "footer.bottom.tagline": "Play More. Pay Less.",
    "footer.refunds": "Refunds & cancellations",

    "legal.sectionLabel": "LEGAL",
    "legal.backToHome": "← Back to home",
    "legal.footerOperatorTitle": "Legal entity",
    "legal.footerOperatorBody":
      "Registered legal name and principal mailing address will appear here after corporate formation and counsel review.",
    "legal.footerOperatorNote": "This site and these policies remain drafts until final sign-off.",

    "legal.refund.title": "Refunds & cancellations",
    "legal.refund.subtitle": "Last updated May 13, 2026. Confirm final language with qualified counsel before relying on this draft with customers.",
    "legal.refund.p1": "Links Golf Membership is an annual membership for eligible Puerto Rico residents. This page summarizes how refunds, choosing not to renew, and billing questions are handled.",
    "legal.refund.p2": "Cooling-off period: You may request a full refund of the membership fee paid within fourteen (14) calendar days of the successful payment date, only if you have not yet redeemed the published Links Golf member discount on a green fee at any partner course. For this rule, \"used\" means the partner course posted your member-priced green fee; complimentary rounds, practice-only visits without that member-priced green fee, or pro shop purchases alone do not count. Email info@linksgolfpr.com from the address on your account with the subject line \"Membership refund request\" and include your full name as shown on the membership.",
    "legal.refund.p3": "After the fourteen-day period, or once you have redeemed the published member discount on a green fee at any partner course, fees are non-refundable except where required or limited by applicable law.",
    "legal.refund.p4": "Non-renewal: If you do not wish to continue in a future year, simply do not renew. Benefits you have already paid for remain available through the expiration date shown on your digital pass.",
    "legal.refund.p5": "Billing disputes: If you believe a charge is incorrect, contact info@linksgolfpr.com before initiating a payment dispute so we can investigate.",
    "legal.refund.p6": "We may update this policy; the \"Last updated\" line above will change when we do. Continued use of the membership after updates constitutes your acknowledgment of the updated policy only to the extent permitted by law.",
    "legal.refund.p7": "Partner courses are independent businesses. Tee times, dress codes, posted rates, and course rules are set by each course.",
    "legal.refund.p8": "If any part of this page conflicts with a separate signed agreement between you and Links Golf PR, the signed agreement controls.",

    "legal.terms.title": "Terms of service (summary draft)",
    "legal.terms.subtitle": "Full legal terms should be reviewed by counsel. This summary is provided for transparency during development.",
    "legal.terms.p1": "By purchasing or using Links Golf Membership you agree to follow these terms, the refund policy, the privacy policy, and each partner course's rules when you play.",
    "legal.terms.p2": "Membership is offered only to individuals who meet published residency requirements and provide accurate information.",
    "legal.terms.p2checkin": "Check-in and discounts: Partner courses may verify your identity when you check in to play (including photo ID when required), consistent with common practice in Puerto Rico and each course's own policies. Your member discount applies only when the course confirms you qualify. False or misleading statements may void your membership.",
    "legal.terms.p3": "Your digital pass is personal, photo-bound, and non-transferable except as expressly permitted in writing by Links Golf PR.",
    "legal.terms.p4": "The roster of partner courses, discount percentages, and rates may change; we will use reasonable efforts to communicate material changes to active members.",
    "legal.terms.p5": "The service is provided \"as available.\" Links Golf PR is not liable for partner course decisions, weather, closures, or events outside its reasonable control.",
    "legal.terms.p6": "Governing law: You agree that disputes will be resolved in accordance with the laws of the Commonwealth of Puerto Rico, unless a different governing law is required for consumers in your jurisdiction.",
    "legal.terms.p7": "Contact: info@linksgolfpr.com",

    "legal.privacy.title": "Privacy policy (summary draft)",
    "legal.privacy.subtitle": "Describe your actual data practices with counsel. This is a concise placeholder aligned with the current signup form fields.",
    "legal.privacy.p1": "We collect the information you submit when joining (such as name, email, phone, mailing address, and membership photo) to provide the membership, identity verification, fraud prevention, and customer support.",
    "legal.privacy.p2": "Payment details you enter on the payment step are handled by our payment processor; we do not store full card numbers on our servers.",
    "legal.privacy.p3": "We use service providers (for example: hosting, email, database, analytics) subject to contracts that require appropriate safeguards.",
    "legal.privacy.p4": "We may email you about renewals, security, or material changes to these policies. You can opt out of marketing messages where applicable using the link in those emails.",
    "legal.privacy.p5": "We retain membership records for as long as needed for legal, tax, accounting, fraud prevention, and operational purposes, then delete or anonymize them according to our internal schedule once confirmed with counsel.",
    "legal.privacy.p6": "Children: Membership is not directed to children under the age required to form a binding contract. Do not submit a child's information.",
    "legal.privacy.p7": "Questions or data requests: info@linksgolfpr.com",

    // Dashboard
    "dashboard.welcome": "Welcome back,",
    "dashboard.memberSince": "Member since",
    "dashboard.renewalDate": "Renewal Date",
    "dashboard.courseAccess": "Course Access",
    "dashboard.courses": "courses",
    "dashboard.support": "Support",
    "dashboard.downloadPass": "Download Pass",
    "dashboard.copyNumber": "Copy Number",
    "dashboard.accountDetails": "Account Details",
    "dashboard.fullName": "Full Name",
    "dashboard.phone": "Phone",
    "dashboard.email": "Email",
    "dashboard.logout": "Logout",
    "dashboard.active": "Active",
    "dashboard.pass.download": "Download pass",
    "dashboard.loadingProfile": "Loading your membership…",
    "dashboard.profileUnavailable":
      "We couldn't load your membership details. The server may be missing SUPABASE_SERVICE_ROLE_KEY, or your record could not be found.",
    "dashboard.retry": "Retry",
    "dashboard.brandTitle": "Links Golf Member",
    "dashboard.pass.memberNo": "Member No.",
    "dashboard.pass.validUntil": "Valid Until",
    "dashboard.pass.showAtProShop": "Show this at pro shop",
    "dashboard.pass.badge": "Founding Member · 2026–27",
    "dashboard.renewalReminder": "You'll receive a renewal reminder 30 days before expiration.",
    "dashboard.coursesCount": "{{count}} courses",
    "dashboard.viewAllCourses": "View all courses",
    "dashboard.needHelp": "Need Help?",
    "dashboard.contactTeam": "Contact our support team",
    "dashboard.editDetails": "Edit Details",
    "dashboard.renewalCardTitle": "Renewal Date",
    "dashboard.courseAccessTitle": "Course Access",
    "dashboard.subscriptionStatus": "Subscription Status",
    "dashboard.subscriptionActive": "Your subscription is active",
    "dashboard.subscriptionInactive": "No active subscription",
    "dashboard.subscriptionCancelPending": "Cancellation pending at renewal",
    "dashboard.renewsOn": "Renews on",
    "dashboard.paymentHistory": "Payment History",
    "dashboard.noPayments": "No payments yet",
    "dashboard.paid": "Paid",
    "dashboard.downloadInvoice": "Download invoice",

    // Login
    "login.title": "Welcome Back",
    "login.subtitle": "Sign in to access your membership and dashboard.",
    "login.email": "Email Address",
    "login.password": "Password",
    "login.signIn": "SIGN IN",
    "login.noAccount": "Don't have an account?",
    "login.signUp": "Sign up here",
    "login.forgotPassword": "Forgot password?",
    "login.memberNotFound": "Member not found. Please sign up first.",
    "login.error": "An error occurred. Please try again.",
    "login.invalidOtp": "Invalid code. Please try again.",
    "login.sending": "Sending…",
    "login.sendOtp": "Send verification code",
    "login.otpSent": "Verification code sent to",
    "login.verificationCode": "Verification code",
    "login.verifying": "Verifying…",
    "login.verify": "Verify and sign in",
    "login.backToEmail": "Back to email",
    "login.welcome": "Welcome back",
    "login.redirecting": "Redirecting to your dashboard…",
  },
  es: {
    // Navigation
    "nav.benefits": "Beneficios",
    "nav.courses": "Campos",
    "nav.howItWorks": "Cómo Funciona",
    "nav.faq": "Preguntas",
    "nav.getCard": "OBTÉN TU MEMBRESIA",
    "nav.login": "Iniciar Sesión",
    "nav.dashboard": "Panel de Control",

    // Sticky mobile CTA (home)
    "sticky.subline": "por año · {{count}} campos",

    // Hero
    "hero.location": "EXCLUSIVO PARA RESIDENTES DE PUERTO RICO",
    "hero.playMore": "Juega Más.",
    "hero.payLess": "Paga Menos.",
    "hero.description": "Una membresía te da acceso a descuentos de hasta 25% en los mejores campos de Puerto Rico — desde TPC Dorado Beach hasta Royal Isabela.",
    "hero.stats.courses": "CAMPOS ASOCIADOS",
    "hero.stats.savings": "AHORROS MÁXIMOS",
    "hero.stats.price": "POR AÑO",
    "hero.cta": "OBTÉN TU MEMBRESIA — $199/AÑO",
    "hero.viewCourses": "VER TODOS LOS CAMPOS",

    // Benefits
    "benefits.label": "POR QUE UNIRSE",
    "benefits.heading": "Por Que Unirse a Links Golf?",
    "benefits.description": "Todo lo que necesitas para jugar mas y pagar menos en los mejores campos de Puerto Rico.",
    "benefits.cta": "HAZTE MIEMBRO",
    "benefits.savings.highlight": "AHORROS INCOMPARABLES",
    "benefits.savings.title": "Ahorra en Cada Ronda",
    "benefits.savings.body": "Ahorra hasta $200 por año con descuentos del 25% en tarifas de green.",
    "benefits.card.highlight": "PASE DIGITAL",
    "benefits.card.title": "Tu Pase, Tu Billetera",
    "benefits.card.body": "ID verificado con foto, no transferible. No se necesita tarjeta física.",
    "benefits.identity.highlight": "ACCESO INSTANTÁNEO",
    "benefits.identity.title": "Juega Inmediatamente",
    "benefits.identity.body": "Juega inmediatamente en los 15 campos asociados con tu pase digital.",
    "benefits.price.highlight": "SIN FECHAS BLOQUEADAS",
    "benefits.price.title": "Juega Cuando Quieras",
    "benefits.price.body": "Juega cuando quieras — entre semana, fines de semana, días festivos.",
    "benefits.stats.partnerCoursesLabel": "Campos asociados",
    "benefits.stats.maxDiscountLabel": "Descuento máximo",
    "benefits.stats.breakEvenLabel": "Rondas para recuperarlo",
    "benefits.stats.breakEvenRange": "3 a 4",

    // Courses
    "courses.label": "NUESTRA RED",
    "courses.heading": "15 Campos Asociados",
    "courses.description": "Juega en los mejores campos de Puerto Rico con tu membresía.",
    "courses.bottomText": "Explora los 15 campos en nuestra red.",
    "courses.viewAll": "Ver directorio completo de campos",
    "courses.filter.all": "TODOS",
    "courses.filter.resort": "RESORT",
    "courses.filter.club": "CLUB",
    "courses.filterLabel": "Filtrar por tipo de campo",
    "courses.discountOff": "DTO",
    "courses.discount": "descuento",
    "courses.mapInfo": "{{count}} campos mostrados",
    "courses.mapCloseDetail": "Cerrar detalle del campo",
    "courses.viewList": "Lista",
    "courses.viewMap": "Mapa",
    "courses.viewModeGroup": "Vista en lista o mapa",
    "courses.homeFilter.all": "Todos",
    "courses.homeFilter.resort": "Resort",
    "courses.homeFilter.semiPrivate": "Semi-privado",
    "courses.homeFilter.public": "Público",
    "courses.homeFilter.countryClub": "Country Club",
    "courses.partner.tpc_dorado_beach": "TPC Dorado Beach Resort & Club",
    "courses.partner.royal_isabela": "Royal Isabela Golf Course",
    "courses.partner.bahia_beach": "Bahía Beach Resort & Golf Club",
    "courses.partner.wyndham_rio_mar": "Wyndham Grand Río Mar",
    "courses.partner.el_conquistador": "El Conquistador Resort",
    "courses.partner.dorado_del_mar": "Dorado del Mar Beach & Golf Resort",
    "courses.partner.el_legado": "El Legado Golf Resort",
    "courses.partner.palmas_del_mar": "Palmas del Mar Country Club",
    "courses.partner.caguas_real": "Caguas Real Golf & Country Club",
    "courses.partner.coco_beach": "Coco Beach Golf & Country Club",
    "courses.partner.club_deportivo_oeste": "Club Deportivo del Oeste",
    "courses.partner.fort_buchanan": "Campo de Golf Fort Buchanan",
    "courses.partner.rio_bayamon": "Campo de Golf Río Bayamón",
    "courses.partner.punta_borinquen": "Campo de Golf Punta Borinquen",
    "courses.partner.costa_caribe": "Costa Caribe Golf Club",

    // How It Works
    "howItWorks.title": "Del registro al primer golpe en minutos.",
    "howItWorks.step1": "Regístrate",
    "howItWorks.step1Desc": "Proporciona tus datos y carga una selfie.",
    "howItWorks.step2": "Obtén Tu Membresía",
    "howItWorks.step2Desc": "El pase digital aparece instantáneamente en tu billetera.",
    "howItWorks.step3": "Juega",
    "howItWorks.step3Desc": "Muestra tu pase en cualquier campo asociado y disfruta tu descuento.",

    // Pricing
    "pricing.title": "Comienza a jugar más hoy.",
    "pricing.subtitle": "Desbloquea todos los campos principales de Puerto Rico. Se paga por sí solo en 3-4 rondas.",
    "pricing.price": "$199",
    "pricing.period": "/año",
    "pricing.residentOnly": "SOLO RESIDENTES DE PUERTO RICO",
    "pricing.details": "DETALLES",
    "pricing.payment": "PAGO",
    "pricing.digitalId": "ID DIGITAL",
    "pricing.annualMembership": "Membresía Anual",
    "pricing.paymentMethodDesc": "Selecciona tu método de pago",
    "pricing.subscribeNow": "Suscribirse Ahora",
    "pricing.buyOnceNow": "Comprar Ahora",
    "pricing.securedByStripe": "Asegurado por Stripe",
    "pricing.playerDetails": "Detalles del Jugador",
    "pricing.firstName": "Nombre",
    "pricing.lastName": "Apellido",
    "pricing.phone": "Teléfono",
    "pricing.email": "Correo Electrónico",
    "pricing.address": "Dirección",
    "pricing.verificationPhoto": "Foto de Verificación",
    "pricing.photoRequired": "Requerido: De frente. Se usa solo para ID Digital.",
    "pricing.takeUploadPhoto": "Tomar o Cargar Foto",
    "pricing.continuePayment": "CONTINUAR AL PAGO",
    "pricing.savingForm": "Guardando…",
    "pricing.savePhoto": "Guardar foto",
    "pricing.choosePhoto": "Elige una foto.",
    "pricing.savePhotoError": "No se pudo guardar la foto. Inténtalo de nuevo.",
    "pricing.memberNoLabel": "N.º de miembro",
    "pricing.validUntilLabel": "Válido hasta",
    "pricing.seasonLabel": "Temporada",
    "pricing.payNow": "PAGAR $199 Y OBTENER TU MEMBRESÍA",
    "pricing.cardNumber": "Número de Tarjeta",
    "pricing.expiry": "VENCIMIENTO",
    "pricing.cvv": "CVV",
    "pricing.nameOnCard": "Nombre en la Tarjeta",
    "pricing.terms": "Términos de Servicio",
    "pricing.privacy": "Política de Privacidad",
    "pricing.agree": "Al continuar, aceptas nuestros",
    "pricing.success": "Ya estás dentro.",
    "pricing.successDesc":
      "Membresía activa. Te enviamos un correo de confirmación.",
    "pricing.postPhotoHeading": "Un último paso: agrega tu foto.",
    "pricing.postPhotoBody":
      "Tu pase de billetera va ligado a la foto; no podemos emitirlo sin una foto verificada. Solo aparece en tu ID digital y no se comparte.",
    "pricing.postPhotoFooter": "Obligatoria · De frente · Solo para tu ID digital.",
    "pricing.savingPhoto": "Guardando…",
    "pricing.walletDisabledHint":
      "Sube tu foto arriba para activar Apple Wallet y Google Wallet.",
    "pricing.addAppleWallet": "Agregar a Apple Wallet",
    "pricing.addGoogleWallet": "Agregar a Google Wallet",
    "pricing.goToDashboard": "IR A MI PANEL",
    "pricing.checkEmail": "Revisa tu correo electrónico para detalles de membresía e información de campos.",
    "pricing.features.courses": "Acceso a 15 campos asociados",
    "pricing.features.savings": "Hasta 25% de descuento en tarifas de green",
    "pricing.features.wallet": "Pase digital en tu billetera",
    "pricing.features.verified": "ID verificado con foto",
    "pricing.features.reissue": "Reemisión gratuita si se pierde",
    "pricing.features.noBlackout": "Sin fechas bloqueadas",

    "pricing.residencyGateTitle": "Confirmar elegibilidad",
    "pricing.residencyCheckbox": "Confirmo que soy residente de buena fe en Puerto Rico.",
    "pricing.agreeTermsLead": "He leído y acepto los",
    "pricing.agreePrivacyLead": "He leído y acepto la",
    "pricing.agreeRefundLead": "He leído",
    "pricing.mustAcceptLegal": "Confirma la elegibilidad y acepta todas las políticas arriba para continuar.",
    "pricing.checkoutHelpLead": "¿Dudas antes de pagar? Escríbenos a ",
    "pricing.paymentRefundReminder": "Estás a punto de pagar la cuota anual. Revisa",

    "memberCard.wordmark": "Membresía Links Golf",

    "trustStrip.headline": "Pensado para jugar todo el año en Puerto Rico",
    "trustStrip.col1Value": "{{count}}",
    "trustStrip.col1Label": "Campos asociados",
    "trustStrip.col2Value": "25%",
    "trustStrip.col2Label": "Ahorro máximo en green fee",
    "trustStrip.col3Value": "365",
    "trustStrip.col3Label": "Días para jugar al año",

    // FAQ
    "faq.label": "PREGUNTAS",
    "faq.heading": "Preguntas frecuentes.",
    "faq.title": "Preguntas frecuentes.",
    "faq.q1": "¿Qué es la Membresía Links Golf?",
    "faq.a1": "Tu membresía todo en uno para golf premium en Puerto Rico. Acceso instantáneo a descuentos exclusivos en todos los campos asociados, un pase de billetera digital e ID de foto verificada — sin tarjeta física necesaria.",
    "faq.q2": "¿Quién puede unirse?",
    "faq.a2": "Solo residentes de Puerto Rico. Al unirte confirmas que cumples nuestras reglas de elegibilidad. Los campos asociados verifican identidad al hacer check-in para jugar (incluida identificación con foto emitida por gobierno cuando lo exijan), práctica habitual en Puerto Rico. Tu descuento de miembro aplica solo cuando el campo confirma que calificas según sus políticas. También podemos solicitar comprobante de residencia o ID en la experiencia de membresía si hace falta para prevenir fraude o brindar soporte. Proporcionar información falsa puede anular tu membresía.",
    "faq.q3": "¿Necesito descargar una aplicación?",
    "faq.a3": "No. Tu membresía vive en la billetera nativa de tu teléfono (Apple Wallet o Google Pay). Solo muestra tu pase en el campo.",
    "faq.q4": "¿Cómo lo uso en el campo?",
    "faq.a4": "Abre tu billetera, muestra tu pase Links Golf a la pro shop y disfruta tu descuento. Es así de simple.",
    "faq.q5": "¿Qué pasa si pierdo mi teléfono?",
    "faq.a5": "Tu pase está vinculado a tu cuenta. Inicia sesión desde cualquier dispositivo y vuelve a agregarlo a tu billetera.",
    "faq.q6": "¿Es la membresía transferible?",
    "faq.a6": "No. Tu pase verificado con foto es no transferible y está vinculado a tu identidad.",
    "faq.q7": "¿Cuándo se renueva mi membresía?",
    "faq.a7": "Tu membresía se renueva anualmente en el aniversario de tu fecha de registro. Recibirás un recordatorio de renovación 30 días antes del vencimiento.",
    "faq.q8": "¿Cómo funcionan los reembolsos y las cancelaciones?",
    "faq.a8Lead": "Lee la política completa aquí:",
    "faq.refundsPageLink": "Reembolsos y cancelaciones",
    "faq.a8Trail": "Explica el plazo de desistimiento, cuándo las cuotas dejan de ser reembolsables y cómo contactarnos por facturación.",
    "faq.stillHaveQuestions": "¿Aún tienes preguntas?",
    "faq.contactUs": "Contáctanos en",

    // Footer
    "footer.tagline": "Desbloquea los mejores campos de Puerto Rico con una membresía.",
    "footer.membership": "MEMBRESÍA",
    "footer.legal": "LEGAL",
    "footer.benefits": "Beneficios",
    "footer.ourNetwork": "Nuestra Red",
    "footer.howItWorks": "Cómo Funciona",
    "footer.getYourCard": "Obtén Tu Membresía",
    "footer.faq": "Preguntas",
    "footer.contactUs": "Contáctanos",
    "footer.email": "info@linksgolfpr.com",
    "footer.copyright": "© 2026 Links Golf. Todos los derechos reservados.",
    "footer.supportTitle": "Soporte",
    "footer.terms": "Términos del Servicio",
    "footer.privacy": "Política de Privacidad",
    "footer.bottom.residency": "© 2026 Links Golf Membership. Solo residentes de Puerto Rico.",
    "footer.bottom.tagline": "Juega más. Paga menos.",
    "footer.refunds": "Reembolsos y cancelaciones",

    "legal.sectionLabel": "LEGAL",
    "legal.backToHome": "← Volver al inicio",
    "legal.footerOperatorTitle": "Entidad legal",
    "legal.footerOperatorBody":
      "El nombre legal registrado y la dirección postal principal aparecerán aquí tras la constitución societaria y revisión legal.",
    "legal.footerOperatorNote": "Este sitio y estas políticas siguen siendo borradores hasta la aprobación final.",

    "legal.refund.title": "Reembolsos y cancelaciones",
    "legal.refund.subtitle": "Última actualización: 13 de mayo de 2026. Confirma el texto final con asesoría legal calificada antes de publicarlo como versión definitiva.",
    "legal.refund.p1": "Links Golf Membership es una membresía anual para residentes elegibles de Puerto Rico. Esta página resume reembolsos, no renovación y consultas de facturación.",
    "legal.refund.p2": "Plazo de desistimiento: puedes solicitar el reembolso íntegro de la cuota pagada dentro de catorce (14) días naturales desde la fecha de pago exitoso, solo si aún no has canjeado el descuento publicado de Links Golf en la tarifa de green en ningún campo asociado. A estos efectos, \"usada\" significa que el campo registró tu green fee con tarifa de miembro; rondas de cortesía, visitas solo de práctica sin ese green fee con tarifa de miembro, o compras únicamente en la pro shop no cuentan. Envía un correo a info@linksgolfpr.com desde la dirección de tu cuenta con asunto \"Solicitud de reembolso de membresía\" e incluye tu nombre completo tal como aparece en la membresía.",
    "legal.refund.p3": "Pasados los catorce días, o una vez que hayas canjeado el descuento publicado de miembro en la tarifa de green en cualquier campo asociado, las cuotas no son reembolsables salvo que la ley aplicable exija o limite lo contrario.",
    "legal.refund.p4": "No renovación: si no deseas continuar el año siguiente, simplemente no renueves. Los beneficios ya pagados siguen vigentes hasta la fecha de vencimiento indicada en tu pase digital.",
    "legal.refund.p5": "Disputas de cargo: si crees que un cargo es incorrecto, contacta info@linksgolfpr.com antes de iniciar una disputa con el banco para que podamos investigar.",
    "legal.refund.p6": "Podemos actualizar esta política; la fecha de \"Última actualización\" cambiará cuando lo hagamos. El uso continuado de la membresía tras cambios constituye tu reconocimiento de la política actualizada en la medida que permita la ley.",
    "legal.refund.p7": "Los campos asociados son negocios independientes. Horarios de salida, códigos de vestimenta, tarifas publicadas y reglas del campo los define cada instalación.",
    "legal.refund.p8": "Si alguna parte de esta página contradice un acuerdo firmado aparte entre tú y Links Golf PR, prevalece el acuerdo firmado.",

    "legal.terms.title": "Términos del servicio (borrador resumido)",
    "legal.terms.subtitle": "Los términos legales completos deben revisarse con abogados. Este resumen es transparencia durante el desarrollo.",
    "legal.terms.p1": "Al comprar o usar Links Golf Membership aceptas estos términos, la política de reembolsos, la de privacidad y las reglas de cada campo cuando juegues.",
    "legal.terms.p2": "La membresía se ofrece solo a personas que cumplan los requisitos de residencia publicados y proporcionen información veraz.",
    "legal.terms.p2checkin": "Check-in y descuentos: los campos asociados pueden verificar tu identidad al hacer check-in para jugar (incluida identificación con foto si lo exigen), de forma acorde a la práctica habitual en Puerto Rico y a las políticas de cada campo. Tu descuento de miembro aplica solo cuando el campo confirma que calificas. Declaraciones falsas o engañosas pueden anular tu membresía.",
    "legal.terms.p3": "Tu pase digital es personal, ligado a tu foto y no transferible salvo autorización expresa por escrito de Links Golf PR.",
    "legal.terms.p4": "La lista de campos, porcentajes de descuento y tarifas puede cambiar; haremos esfuerzos razonables para comunicar cambios importantes a miembros activos.",
    "legal.terms.p5": "El servicio se ofrece \"según disponibilidad\". Links Golf PR no responde por decisiones del campo, clima, cierres u otros eventos fuera de su control razonable.",
    "legal.terms.p6": "Ley aplicable: acuerdas que las disputas se resolverán conforme a las leyes del Estado Libre Asociado de Puerto Rico, salvo que otra ley sea obligatoria para consumidores en tu jurisdicción.",
    "legal.terms.p7": "Contacto: info@linksgolfpr.com",

    "legal.privacy.title": "Política de privacidad (borrador resumido)",
    "legal.privacy.subtitle": "Describe con abogados las prácticas reales de datos. Este texto es un marcador de posición alineado con los campos actuales del formulario.",
    "legal.privacy.p1": "Recopilamos la información que envías al unirte (nombre, correo, teléfono, dirección postal y foto de membresía) para prestar la membresía, verificar identidad, prevenir fraude y brindar soporte.",
    "legal.privacy.p2": "Los datos de pago del paso de pago los procesa nuestro proveedor de pagos; no almacenamos números completos de tarjeta en nuestros servidores.",
    "legal.privacy.p3": "Usamos proveedores (p. ej. alojamiento, correo, base de datos, analítica) con contratos que exigen salvaguardas adecuadas.",
    "legal.privacy.p4": "Podemos enviarte correos sobre renovaciones, seguridad o cambios importantes a estas políticas. Puedes darte de baja de mensajes de marketing cuando aplique usando el enlace de esos correos.",
    "legal.privacy.p5": "Conservamos registros de membresía el tiempo necesario para fines legales, fiscales, contables, antifraude y operativos; luego los eliminamos o anonimizamos según calendario interno confirmado con asesoría.",
    "legal.privacy.p6": "Menores: la membresía no está dirigida a menores sin capacidad legal para contratar. No envíes datos de menores.",
    "legal.privacy.p7": "Consultas o solicitudes de datos: info@linksgolfpr.com",

    // Dashboard
    "dashboard.welcome": "Bienvenido de vuelta,",
    "dashboard.memberSince": "Miembro desde",
    "dashboard.renewalDate": "Fecha de Renovación",
    "dashboard.courseAccess": "Acceso a Campos",
    "dashboard.courses": "campos",
    "dashboard.support": "Soporte",
    "dashboard.downloadPass": "Descargar Pase",
    "dashboard.copyNumber": "Copiar Número",
    "dashboard.accountDetails": "Detalles de la Cuenta",
    "dashboard.fullName": "Nombre Completo",
    "dashboard.phone": "Teléfono",
    "dashboard.email": "Correo Electrónico",
    "dashboard.logout": "Cerrar Sesión",
    "dashboard.active": "Activo",
    "dashboard.pass.download": "Descargar pase",
    "dashboard.loadingProfile": "Cargando tu membresía…",
    "dashboard.profileUnavailable":
      "No pudimos cargar los datos de tu membresía. Puede faltar SUPABASE_SERVICE_ROLE_KEY en el servidor, o no encontramos tu registro.",
    "dashboard.retry": "Reintentar",
    "dashboard.brandTitle": "Miembro Links Golf",
    "dashboard.pass.memberNo": "N.º de miembro",
    "dashboard.pass.validUntil": "Válido hasta",
    "dashboard.pass.showAtProShop": "Muéstralo en la pro shop",
    "dashboard.pass.badge": "Miembro fundador · 2026–27",
    "dashboard.renewalReminder": "Recibirás un recordatorio de renovación 30 días antes del vencimiento.",
    "dashboard.coursesCount": "{{count}} campos",
    "dashboard.viewAllCourses": "Ver todos los campos",
    "dashboard.needHelp": "¿Necesitas ayuda?",
    "dashboard.contactTeam": "Contacta a nuestro equipo de soporte",
    "dashboard.editDetails": "Editar datos",
    "dashboard.renewalCardTitle": "Fecha de Renovación",
    "dashboard.courseAccessTitle": "Acceso a Campos",
    "dashboard.subscriptionStatus": "Estado de Suscripción",
    "dashboard.subscriptionActive": "Tu suscripción está activa",
    "dashboard.subscriptionInactive": "Sin suscripción activa",
    "dashboard.subscriptionCancelPending": "Cancelación pendiente en renovación",
    "dashboard.renewsOn": "Se renueva el",
    "dashboard.paymentHistory": "Historial de Pagos",
    "dashboard.noPayments": "Sin pagos aún",
    "dashboard.paid": "Pagado",
    "dashboard.downloadInvoice": "Descargar factura",

    // Login
    "login.title": "Bienvenido de Vuelta",
    "login.subtitle": "Inicia sesión para acceder a tu membresía y panel.",
    "login.email": "Correo Electrónico",
    "login.password": "Contraseña",
    "login.signIn": "INICIAR SESIÓN",
    "login.noAccount": "¿No tienes cuenta?",
    "login.signUp": "Regístrate aquí",
    "login.forgotPassword": "¿Olvidaste tu contraseña?",
    "login.memberNotFound": "Miembro no encontrado. Regístrate primero.",
    "login.error": "Ocurrió un error. Inténtalo de nuevo.",
    "login.invalidOtp": "Código no válido. Inténtalo de nuevo.",
    "login.sending": "Enviando…",
    "login.sendOtp": "Enviar código de verificación",
    "login.otpSent": "Código de verificación enviado a",
    "login.verificationCode": "Código de verificación",
    "login.verifying": "Verificando…",
    "login.verify": "Verificar e iniciar sesión",
    "login.backToEmail": "Volver al correo",
    "login.welcome": "Bienvenido de nuevo",
    "login.redirecting": "Redirigiendo a tu panel…",
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    // Initialize from localStorage if available
    if (typeof window !== "undefined") {
      const saved = localStorage.getItem("language") as Language | null;
      if (saved && (saved === "en" || saved === "es")) {
        return saved;
      }
    }
    return "en";
  });

  // Save to localStorage whenever language changes
  useEffect(() => {
    if (typeof window !== "undefined") {
      localStorage.setItem("language", language);
    }
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    let s = translations[language][key] || key;
    if (params) {
      for (const [k, v] of Object.entries(params)) {
        s = s.replaceAll(`{{${k}}}`, String(v));
      }
    }
    return s;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
